### ISSUE TITLE
Question about the output.txt

### ISSUE THREAD

**Issue by LeiShenVictoria** [declare-lab/MIME#2]
Hi,
 I found that the responses provided in output.txt are not similar to what you mentioned in your paper.

E.g.,
emotion:apprehensive	vader-score: -0.6606	predicted_emotion: afraid
Context:['i went skydiving last summer with my partner . it was so scary !', 'wow , that is scary . were you nervous ?', 'absolutely ! i have always been scared of heights , but i am so glad i made myself .']
Topk:that sounds like fun ! 
Beam: i am sorry to hear that . i hope you have a good time ! 
Greedy:i am sorry to hear that . i hope you get it ! 
Ref:it sounds like a great experience !

While the response for this case in your paper is "That must've been a very beautiful memory."

**Comment by nmder** [comment]
Hi,

This is normal as there is randomness in the model stemmed from sampling. Hope this resolves your doubt.

Thanks!

**Comment by LeiShenVictoria** [comment]
Could you pls provide the output.txt you used in your paper?
Thanks
